# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider', verbose_name='产品图片'),
        ),
    ]
