# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0006_auto_20170622_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firstclass',
        ),
        migrations.AddField(
            model_name='product',
            name='au_second_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='澳洲二程$'),
        ),
        migrations.AddField(
            model_name='product',
            name='de_second_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='德国二程€'),
        ),
        migrations.AddField(
            model_name='product',
            name='uk_second_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='英国二程£'),
        ),
        migrations.AddField(
            model_name='product',
            name='us_second_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='美国二程$'),
        ),
    ]
