# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0008_auto_20170622_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.CharField(default='A组', max_length=20, verbose_name='开发者'),
        ),
    ]
