# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0010_auto_20170623_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='产品图片'),
        ),
    ]
