# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0011_auto_20170623_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_time',
            field=models.DateField(default=datetime.date(2017, 6, 23), verbose_name='上架时间'),
        ),
    ]
