# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0012_product_added_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_time',
        ),
    ]
