# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0013_remove_product_added_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cn_au_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='澳洲小包$'),
        ),
        migrations.AddField(
            model_name='product',
            name='cn_de_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='德国小包€'),
        ),
        migrations.AddField(
            model_name='product',
            name='cn_uk_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='英国小包£'),
        ),
        migrations.AddField(
            model_name='product',
            name='cn_us_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='美国小包$'),
        ),
        migrations.AlterField(
            model_name='product',
            name='au_second_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='澳洲二程$'),
        ),
        migrations.AlterField(
            model_name='product',
            name='de_second_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='德国二程€'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uk_second_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='英国二程£'),
        ),
        migrations.AlterField(
            model_name='product',
            name='us_second_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='美国二程$'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='体积m³'),
        ),
    ]
