# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0015_auto_20170627_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='目录'),
            preserve_default=False,
        ),
    ]
