# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0016_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='File')),
                ('name', models.CharField(max_length=50, verbose_name='文件名')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
