# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-12 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0019_hotssle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='目录')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('item_id', models.IntegerField(verbose_name='产品ID')),
                ('image', models.URLField(blank=True, null=True, verbose_name='产品图片')),
            ],
            options={
                'verbose_name': '热卖跟踪',
                'verbose_name_plural': '热卖跟踪',
                'ordering': ('sku',),
            },
        ),
        migrations.DeleteModel(
            name='HotSsle',
        ),
    ]
