# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0020_auto_20170712_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotsale',
            name='competitor_us_price',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='竞争对手价格'),
            preserve_default=False,
        ),
    ]
