# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0022_remove_hotsale_competitor_us_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotsale',
            options={'verbose_name': '热卖跟踪', 'verbose_name_plural': '热卖跟踪'},
        ),
        migrations.RemoveField(
            model_name='hotsale',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='hotsale',
            name='sku',
        ),
        migrations.AddField(
            model_name='hotsale',
            name='competitor_price',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='竞争对手价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotsale',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='竞争对手链接'),
            preserve_default=False,
        ),
    ]
