# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0023_auto_20170713_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
