# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-05 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0024_auto_20170831_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='目录'),
        ),
    ]
