# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0027_auto_20170909_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingtime',
            name='date',
        ),
        migrations.AlterField(
            model_name='shippingtime',
            name='timeIn',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='shippingtime',
            name='timeOut',
            field=models.DateField(null=True),
        ),
    ]
