# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0029_auto_20170911_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingtime',
            name='timeOut',
        ),
        migrations.AddField(
            model_name='shippingtime',
            name='onway_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='在途时间'),
        ),
    ]
