# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0030_auto_20170911_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingtime',
            name='onway_days',
        ),
        migrations.AddField(
            model_name='shippingtime',
            name='future_time',
            field=models.DateField(blank=True, null=True, verbose_name='上架时间'),
        ),
    ]
