# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0031_auto_20170912_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingtime',
            name='future_time',
        ),
        migrations.AddField(
            model_name='shippingtime',
            name='date',
            field=models.IntegerField(blank=True, null=True, verbose_name='日'),
        ),
        migrations.AddField(
            model_name='shippingtime',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='月'),
        ),
        migrations.AddField(
            model_name='shippingtime',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='年'),
        ),
    ]
