# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0032_auto_20170912_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='au_second_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cn_au_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cn_de_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cn_uk_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cn_us_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='de_second_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uk_second_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='us_second_cost',
        ),
    ]
