# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0037_auto_20171208_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume',
        ),
        migrations.AddField(
            model_name='product',
            name='Longest_side',
            field=models.FloatField(blank=True, null=True, verbose_name='长cm'),
        ),
        migrations.AddField(
            model_name='product',
            name='Median_side',
            field=models.FloatField(blank=True, null=True, verbose_name='中cm'),
        ),
        migrations.AddField(
            model_name='product',
            name='Shortest_side',
            field=models.FloatField(blank=True, null=True, verbose_name='短cm'),
        ),
    ]
